import { Injectable } from '@angular/core';

import type { 
EnhancedTextItem,
  InspectTextItem,
  HtmlTextItem,
PdfTextItemLike,
  PdfTextStyleLike,
  PdfViewportLike,

  LinkRect} from '../services/pdf_interface';
import { PdfFontDictionaryService, PdfFontDefinition } from '../services/pdf-font-dictionary';
import { GoogleFontService } from '../mainscreen/fonts/font-catalog';
import * as pdfjsLib from 'pdfjs-dist';
import { MuPdfTextItem } from './mupdf/pdf-extract.service';
@Injectable({
  providedIn: 'root',
})
export class Textconverter {




  constructor()
  {

  (pdfjsLib.GlobalWorkerOptions as { workerSrc: string }).workerSrc = 'pdf.worker.mjs';
  }


 htmlItemsFromMuPdf(
  runs: MuPdfTextItem[],
  pageId:string,
  links:LinkRect[] = []
):HtmlTextItem[] {


 const items:HtmlTextItem[] = [];


 for(
   let index=0;
   index < runs.length;
   index++
 ){

   const run =
     runs[index];


   const text =
     run.text
       ?.replace(/\s+/g,' ')
       .trim();


   if(!text)
     continue;


   const isLinked =
    links.some(link =>
      rectsOverlap(
        {
          x:run.bbox.x,
          y:run.bbox.y,
          width:run.bbox.w,
          height:run.bbox.h
        },
        link
      )
    );



   const font =
     this.cleanMuPdfFont(
       run.fontName
     );




   items.push({

    id:
     `${pageId}-mupdf-${index}`,


    pageId,


    text,


    x:
     run.bbox.x,


    y:
     run.bbox.y,

width:
  Math.max(
    30,
    run.bbox.w + 10
  ),

height:
  Math.max(
    run.size * 1.45,
    run.bbox.h + 4
  ),


// keep original PDF area
originalX:
  run.bbox.x,

originalY:
  run.bbox.y,

originalWidth:
  run.bbox.w,

originalHeight:
  run.bbox.h,



    size:
     run.size,


    fontFamily:
     font,


    fontWeight:
     run.weight,


    fontStyle:
     run.style,


    color:
     isLinked
      ? '#0000ee'
      : '#111111',



    textDecoration:
     isLinked
      ? 'underline'
      : undefined,



    backgroundColor:
      '#ffffff',



    originalText:
      text,


    originalSize:
      run.size,


    originalColor:
     isLinked
      ? '#0000ee'
      : '#111111',


    originalFontWeight:
      run.weight,


    originalFontStyle:
      run.style,



    textAlign:'left'

   });


 }


 return items;

}

private  cleanMuPdfFont(
 font:string
){

 if(!font)
   return 'Times New Roman';


 return font
  .replace(
    /^[A-Z]{6}\+/,
    ''
  )
  .replace(
    '-Bold',
    ''
  );

}

//  htmlItemsFromTextContent(
//   content: { items: unknown[]; styles?: Record<string, PdfTextStyleLike> },
//   viewport: PdfViewportLike,
//   pageId: string,
//   links: LinkRect[] = [],
//   operatorList?: any
// ): HtmlTextItem[] {
//   const rawItems = this.rawItemsFromTextContent(content, viewport, pageId, operatorList);
//   if (!rawItems.length) return [];

//   // Deep Operator Stream Scanner Engine
//   const operatorFontMap = new Map<string, string>();
//   if (operatorList && operatorList.fnArray && operatorList.argsArray) {
//     try {
//       for (let i = 0; i < operatorList.fnArray.length; i++) {
//         if (operatorList.fnArray[i] === 33 || operatorList.fnArray[i] === 'setFont') {
//           const args = operatorList.argsArray[i];
//           if (args && args.length >= 1) {
//             const fontRefKey = String(args[0]).toLowerCase().trim();
//             if (args[1] && typeof args[1] === 'string') {
//               operatorFontMap.set(fontRefKey, args[1]);
//             } else if (typeof args[0] === 'string') {
//               operatorFontMap.set(fontRefKey, args[0]);
//             }
//           }
//         }
//       }
//     } catch (opError) {
//       console.warn('Operator stream metadata sweep paused.', opError);
//     }
//   }


//   // 1. Core Typography Layer
//   const initialMappedItems: EnhancedTextItem[] = rawItems.map((item, index) => {
//     const rawItem = item as any;
//     const nativeItem = content.items[index] as any;
//     const fontKey = nativeItem?.fontName || '';
//     const normalizedFontKey = fontKey.toLowerCase().trim();
    
//     // SAFE SCOPE DECLARATION FIRST
//     const matchedStyle = (content.styles && fontKey) ? content.styles[fontKey] : null;
//     const operatorMappedName = operatorFontMap.get(normalizedFontKey) || '';

//     // Collate all metadata references generated by the layout engine
//     const rawCandidates = [
//       operatorMappedName,
//       matchedStyle?.fontFamily,
//       (matchedStyle as any)?.name,
//       rawItem?.fontFamily,
//       rawItem?.fontName,
//       nativeItem?.fontName,
//       fontKey
//     ].filter((name): name is string => typeof name === 'string' && name.trim().length > 0);

//     // 🔥 FIX DETECTOR: Split long fallback lists up and clean each string item individually
//     const candidateNames: string[] = [];
//     for (const entry of rawCandidates) {
//       // Split on commas or spaces to isolate single font tokens (e.g. "Times New Roman" or "g_d0_f1")
//       const subTokens = entry.split(/[,]+/);
//       for (const token of subTokens) {
//         const cleanToken = token.replace(/['"]/g, '').trim();
//         if (cleanToken && !candidateNames.includes(cleanToken)) {
//           candidateNames.push(cleanToken);
//         }
//       }
//     }

//     let exactMatchFound: any = null;
//     const fontsArray = (this.pdfFonts as any[]) || [];

//     // Tier 1: Try strict match on candidate naming strings against your accurate registry
//     for (const rawName of candidateNames) {
//       const cleanedCandidate = this.pdfFontDictionary.cleanFontName(rawName).toLowerCase().trim();
      
//       exactMatchFound = fontsArray.find((f: any) => 
//         this.pdfFontDictionary.cleanFontName(f.baseFont).toLowerCase().trim() === cleanedCandidate ||
//         f.baseFont.toLowerCase().trim() === cleanedCandidate
//       );

//       if (exactMatchFound) break;
//     }

//     // =========================================================================
//     // 🔥 CRITICAL FIXED LOGIC: FORCE BOLD CHECK VIA VISUAL DENSITY PROFILER
//     // =========================================================================
//     const textStr = (item.text || '').replace(/\s+/g, ' ').trim();
//     const textCandidateString = candidateNames.join(' ');
//     const hasItalicKeyword = /italic|oblique|it/i.test(textCandidateString) || /italic|oblique/i.test(fontKey);

//     // 1. Check metadata signatures
//     const hasBoldNameToken = /bold|black|heavy|semibold|demibold|bd|w00/i.test(textCandidateString) || 
//                              /bold|black/i.test(fontKey);
//     const styleFontFamily = matchedStyle?.fontFamily || '';
//     const isBoldInStyle = /bold|black|heavy|700|800/i.test(styleFontFamily);
//     const isLargeHeading = item.size >= 14 || item.height >= 14;

//     // 2. Compute true canvas footprint metric ratios
//     const charCount = textStr.length || 1;
//     const avgCharWidth = item.width / charCount;
//     const widthFactorAt11pt = (avgCharWidth / item.size) * 11;
    
//     // For short introduction blocks ("To,", "From,") the footprint stretches wide
//     const isShortBoldHeader = charCount <= 10 && widthFactorAt11pt > 5.5;
//     const isLongBoldRow = charCount > 10 && widthFactorAt11pt > 5.8;
//     const isVisuallyThick = isShortBoldHeader || isLongBoldRow;

//     // Decide absolute requirement state
//     const requiresBold = hasBoldNameToken || isBoldInStyle || isLargeHeading || isVisuallyThick;

//     // OVERRIDE TIER: Sync matching profile results explicitly with the visual layout density requirements
//     if (fontsArray.length > 0) {
//       const bestStyleMatch = fontsArray.find((f: any) => f.bold === requiresBold && f.italic === hasItalicKeyword) || 
//                              fontsArray.find((f: any) => f.bold === requiresBold);
      
//       if (bestStyleMatch) {
//         exactMatchFound = bestStyleMatch;
//       }
//     }

//     // Extract true styling parameters directly from your verified parsing registry data
//     let trueFontFamilyName = 'Cambria'; 
//     let isFontBold = false;
//     let isFontItalic = false;

//   if (exactMatchFound) {
//   trueFontFamilyName = exactMatchFound.baseFont; 
//   isFontBold = exactMatchFound.bold;
//   isFontItalic = exactMatchFound.italic;
// } else if (fontsArray.length > 0) {
//   // Use the find result, or default to the first available font object
//   const fallbackProfile = fontsArray.find((f: any) => f.bold === requiresBold) || fontsArray[0];
  
//   trueFontFamilyName = fallbackProfile.baseFont;
//   isFontBold = fallbackProfile.bold;
//   isFontItalic = fallbackProfile.italic;
// }
// // Add a guard clause before normalization
// if (!trueFontFamilyName) {
//     console.error("Critical Error: Font family name is null/undefined. Defaulting to 'Arial'.");
//     trueFontFamilyName = 'Arial';
// }

// const cleanFontFamily = trueFontFamilyName.replace(/Bold|Italic|Regular/gi, '').trim();
// //console.log('Font Family Normalization:', { rawCandidates, candidateNames, exactMatchFound, cleanFontFamily, isFontBold, isFontItalic });
//     // Standardise rendering fallbacks cleanly
//     let finalFontFamily = cleanFontFamily;
//     if (/times/i.test(cleanFontFamily)) finalFontFamily = 'Times New Roman';
//     if (/cambria/i.test(cleanFontFamily)) finalFontFamily = 'Cambria';
//     if (/calibri/i.test(cleanFontFamily)) finalFontFamily = 'Calibri';
//     if (/helvetica/i.test(cleanFontFamily)) finalFontFamily = 'Helvetica';

//     // Build the dynamic platform fallback typography style stacks
//     const isSerifStyle = /serif|times|cambria|georgia|garamond/i.test(finalFontFamily);
//     const fallbackStack = isSerifStyle 
//       ? `"${finalFontFamily}", Georgia, serif` 
//       : `"${finalFontFamily}", Arial, sans-serif`;

//     // Trigger your service loader to mount the style onto the web layout view context
//     this.fontService.loadFontToDOM(finalFontFamily);

//     return {
//       ...item,
//       fontFamily: fallbackStack, // Feeds straight into your inline templates via textItem.fontFamily
//       fontWeight: isFontBold ? '700' : '400',
//       fontStyle: isFontItalic ? 'italic' : 'normal',
//       cleanText: textStr,
//       color: rawItem.color || '#111111'
//     } as unknown as EnhancedTextItem;
//   });





//   // 2. Core Geometric Spatial Deduplication Layer
//   const spatialDeduplicatedItems: EnhancedTextItem[] = [];
//   for (const currentItem of initialMappedItems) {
//     const isSpatialCollision = spatialDeduplicatedItems.some(existingItem => {
//       const verticalOverlap = Math.abs(existingItem.y - currentItem.y) < Math.max(existingItem.size, currentItem.size) * 0.3;
//       const horizontalOverlap = Math.abs(existingItem.x - currentItem.x) < 5;
//       if (verticalOverlap && horizontalOverlap) {
//         return true;
//       }
//       const xOverlap = (currentItem.x >= existingItem.x && currentItem.x <= (existingItem.x + existingItem.width)) || 
//                        (existingItem.x >= currentItem.x && existingItem.x <= (currentItem.x + currentItem.width));
//       const yOverlap = Math.abs(existingItem.y - currentItem.y) < 3;
//       if (xOverlap && yOverlap) {
//         if (existingItem.text.length >= currentItem.text.length) {
//           return true;
//         }
//       }
//       return false;
//     });
//     if (!isSpatialCollision) {
//       spatialDeduplicatedItems.push(currentItem);
//     }
//   }

//   spatialDeduplicatedItems.sort((a, b) => {
//     const yBucketA = Math.round(a.y * 10) / 10;
//     const yBucketB = Math.round(b.y * 10) / 10;
//     const rowDiff = yBucketA - yBucketB;
//     if (Math.abs(rowDiff) > Math.max(a.size, b.size) * 0.45) {
//       return rowDiff;
//     }
//     return a.x - b.x;
//   });

//   // 3. Assemble Line Rows with Text Boundary Checking
//   const lines: EnhancedTextItem[][] = [];
//   for (const item of spatialDeduplicatedItems) {
//     if (!item.cleanText) continue;
//     let added = false;
//     const lookbackLimit = Math.max(0, lines.length - 4);
//     for (let i = lines.length - 1; i >= lookbackLimit; i--) {
//       const activeLine = lines[i];
//       const referenceItem = activeLine[0];
//       if (referenceItem && Math.abs(referenceItem.y - item.y) <= Math.max(referenceItem.size, item.size) * 0.55) {
//         activeLine.push(item);
//         added = true;
//         break;
//       }
//     }
//     if (!added) {
//       lines.push([item]);
//     }
//   }

//   // 4. Flatten grouped line components into distinct horizontal text chunks
//   const finalItems = lines.flatMap((line, lineIndex) => {
//     line.sort((a, b) => a.x - b.x);
//     const maxLineSize = Math.max(...line.map(item => item.size));
//     const normalizedSize = Math.max(8, Math.round(maxLineSize * 0.97));
//     const segments: EnhancedTextItem[][] = [];
//     let currentSegment: EnhancedTextItem[] = [];
//     let previousXEnd = line[0]?.x ?? 0;

//     for (const item of line) {
//       const gap = currentSegment.length ? item.x - previousXEnd : 0;
//       const averageCharWidth = Math.max(2, item.width / Math.max(item.cleanText.length, 1));
//       const adaptiveGapThreshold = Math.max(normalizedSize * 0.85, averageCharWidth * 2.2);
//       if (currentSegment.length && gap > adaptiveGapThreshold) {
//         segments.push(currentSegment);
//         currentSegment = [];
//       }
//       currentSegment.push(item);
//       previousXEnd = item.x + item.width;
//     }
//     if (currentSegment.length) segments.push(currentSegment);
//     return segments.map((segment, segmentIndex) => this.htmlItemFromLineSegment(segment, links, pageId, lineIndex, segmentIndex));
//   });

//   // 5. Universal Inversion Adjustment Filter Layer
//   return finalItems.map(item => {
//     const bg = (item.backgroundColor || '').replace(/\s+/g, '').toLowerCase();
//     const textFill = (item.color || '').replace(/\s+/g, '').toLowerCase();
//     const isInvertedProblemColor = bg !== 'transparent' && bg !== '#ffffff' && bg !== 'rgba(0,0,0,0)';
//     const isDarkDefaultText = /^(#111111|#000000|rgb\(17,17,17\)|rgb\(0,0,0\))$/.test(textFill);
//     if (isInvertedProblemColor && isDarkDefaultText) {
//       const realTextColor = item.backgroundColor;
//       return {
//         ...item,
//         color: realTextColor,
//         backgroundColor: '#ffffff',
//         originalColor: realTextColor,
//       };
//     }
//     return item;
//   }).filter(item => item.text.trim().length > 0);
// }

//  htmlItemFromLineSegment(
//   ordered: InspectTextItem[], 
//   links: LinkRect[], 
//   pageId: string, 
//   lineIndex: number, 
//   segmentIndex: number
// ): HtmlTextItem {
//   const first = ordered[0]; 
//   const last = ordered[ordered.length - 1];
//   const size = Math.max(...ordered.map((item) => item.size));
  
//   let text = '';
//   let previousEnd = first.x;
  
//   for (const item of ordered) {
//     const clean = item.text.replace(/\s+/g, ' ').trim();
//     if (!clean) continue;
//     const averageCharWidth = Math.max(2, item.width / Math.max(clean.length, 1));
//     const gap = item.x - previousEnd;
//     if (text && gap > averageCharWidth * 0.35) {
//       text += ' ';
//     }
//     text += clean;
//     previousEnd = item.x + item.width;
//   }
  
//   const isLinked = ordered.some((item) => links.some((link) => this.rectsOverlap(item, link)));
//   const textStr = text.trim();
//   const enhancedFirst = first as any;

//   // ─── NON-DESTRUCTIVE UNIVERSAL FONT RESOLVER ───
//   // Preserves genuine fonts (like Times New Roman) so your dropdown side panel highlights it perfectly on-click
//   let finalFontFamily = enhancedFirst?.exactFont || first?.fontFamily || '';
  
//   if (finalFontFamily) {
//     finalFontFamily = finalFontFamily.split(',')[0].replace(/['"]/g, '').trim();
//   }

//   // Force clean standard fallbacks only if fields are completely broken, missing, or plain generic strings
//   if (!finalFontFamily || finalFontFamily.toLowerCase() === 'serif' || finalFontFamily.toLowerCase() === 'sans-serif') {
//     finalFontFamily = 'Arial'; 
//   }

//   // Headings & Bold rules text heuristics
//   const isHeaderSize = size >= 14 || Math.max(...ordered.map(i => i.height)) >= 14;
//   const hasBoldKeyword = /bold|black|heavy|w00/i.test(finalFontFamily) || first?.fontWeight === '700';
//   const isNumberedSection = /^\d+[\d\.]*\s*[A-Z]/.test(textStr);
//   const isAllCapsHeading = textStr.length > 3 && textStr.length < 60 && textStr === textStr.toUpperCase() && /[A-Z]/.test(textStr);

//   const verifyBoldThickness = hasBoldKeyword || isHeaderSize || isNumberedSection || isAllCapsHeading;
//   const finalFontWeight = verifyBoldThickness ? '700' : '400';
//   const finalFontStyle = enhancedFirst?.fontStyle || first?.fontStyle || 'normal';

//   // Sizing matrix constraints: Adds a small padding buffer to accommodate bold letter expansions without clipping
//   const calculatedWidth = last.x + last.width - first.x;
//   const dynamicBoundingWidth = Math.max(24, calculatedWidth + 6); 
//   const dynamicBoundingHeight = Math.max(size * 1.35, ...ordered.map((item) => item.height));

//   return {
//     id: `${pageId}-html-line-${lineIndex}-${segmentIndex}`,
//     pageId,
//     text: textStr,
//     x: first.x,
//     y: Math.min(...ordered.map((item) => item.y)),
//     width: dynamicBoundingWidth,
//     height: dynamicBoundingHeight,
//     size,
    
//     fontFamily: finalFontFamily,      // Clean isolated naming passed directly to view models
//     fontWeight: finalFontWeight,
//     fontStyle: finalFontStyle,
    
//     color: isLinked ? '#0000ee' : first.color ?? '#111111',
//     textDecoration: isLinked ? 'underline' : undefined,
//     backgroundColor: '#ffffff',       // 👈 Enforces solid white background to mask fuzzy canvas duplicates underneath
    
//     originalText: textStr,
//     originalSize: size,
//     originalColor: isLinked ? '#0000ee' : first.color ?? '#111111',
//     originalFontWeight: finalFontWeight,
//     originalFontStyle: finalFontStyle,
//     textAlign: 'left',
//   };
// }
   rectsOverlap(a: Pick<InspectTextItem, 'x' | 'y' | 'width' | 'height'>, b: LinkRect): boolean {
    return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;
  }
   rawItemsFromTextContent(
    content: { items: unknown[]; styles?: Record<string, PdfTextStyleLike> }, 
    viewport: PdfViewportLike, 
    pageId: string,
    operatorList?: any // Injected operator tracking stream object
  ): InspectTextItem[] {
    const util = (pdfjsLib as unknown as { Util: { transform: (m1: number[], m2: number[]) => number[] } }).Util;
    
    // Build a lookup map of text color profiles indexed by active stream position keys
    const operatorColorMap: Record<number, string> = {};
    let activeColorCode = '#111111'; // Core base fallback template tint
  
    if (operatorList && operatorList.fnArray) {
      for (let i = 0; i < operatorList.fnArray.length; i++) {
        const fnId = operatorList.fnArray[i];
        const args = operatorList.argsArray[i];
  
        // Detect PDF canvas text-painting brush configurations (e.g. setFillRGBColor)
        if (fnId === (pdfjsLib as any).OPS?.setFillRGBColor && args) {
          const r = args[0], g = args[1], b = args[2];
          activeColorCode = `#${((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1)}`;
        } else if (fnId === (pdfjsLib as any).OPS?.showText || fnId === (pdfjsLib as any).OPS?.showTextGLYPHS) {
          operatorColorMap[i] = activeColorCode;
        }
      }
    }
    
    return content.items
      .filter((item): item is PdfTextItemLike => this.isPdfTextItem(item))
      .map((item, index) => {
        const transform = util.transform(viewport.transform, item.transform);
        const size = Math.max(8, Math.hypot(transform[2], transform[3]));
        const heightFromText = item.height || size * 1.05;
        const sizeFromHeight = Math.max(8, heightFromText * 0.82);
        const fontSize = Math.max(size, sizeFromHeight);
        const width = Math.max(10, item.width || item.str.length * fontSize * 0.55);
        const height = Math.max(10, item.height || fontSize * 1.08);
        

const style = item.fontName ? content.styles?.[item.fontName] : undefined;
console.log('DEBUG FONT:', { 
    fontName: item.fontName, 
    styleFamily: style?.fontFamily, 
    label: `${item.fontName ?? ''} ${style?.fontFamily ?? ''}` 
});
        const fontLabel = `${item.fontName ?? ''} ${style?.fontFamily ?? ''}`;
        const isBold = /bold|black|heavy|demi|semi|w00/i.test(fontLabel);
  
        // Extract the precise font text color from the matching vector graphics state index
        const finalTextColor = operatorColorMap[index] || (item as any).color || '#111111';
  
        return {
          id: `${pageId}-run-${index}`,
          text: item.str,
          x: transform[4],
          y: transform[5] - height,
          width,
          height,
          size: fontSize,
          fontName: item.fontName, 
          fontFamily: this.pdfFontFamily(style?.fontFamily, item.fontName),
          fontWeight: isBold ? '700' : '400',
          fontStyle: /italic|oblique/i.test(fontLabel) ? 'italic' : 'normal',
          color: finalTextColor,              // Navy blue (#08466f) applies here correctly
          backgroundColor: 'transparent'      // Preserves text rendering transparency bounds
        };
      })
      .filter((item) => item.text.trim().length > 0 && item.width > 2 && item.height > 2);
  }
pdfFontFamily(fontFamily?: string, fontName?: string): string {
    const label = `${fontFamily ?? ''} ${fontName ?? ''}`.toLowerCase();
    
    // Explicit priority check
    if (label.includes('arial') || label.includes('helvetica') || label.includes('sans')) {
        return 'Arial, Helvetica, sans-serif';
    }
    if (label.includes('courier') || label.includes('mono')) {
        return 'Courier New, Courier, monospace';
    }
    // Only default to Times/Cambria if no other indicators are found
    if (label.includes('times') || label.includes('serif') || label.includes('cambria')) {
        return 'Times New Roman, Georgia, serif';
    }
    
    return 'Arial, Helvetica, sans-serif'; // Safer general fallback
}
     isPdfTextItem(item: unknown): item is PdfTextItemLike {
    if (!item || typeof item !== 'object') return false;
    const candidate = item as Partial<PdfTextItemLike>;
    return typeof candidate.str === 'string'
      && candidate.str.trim().length > 0
      && Array.isArray(candidate.transform)
      && typeof candidate.width === 'number'
      && typeof candidate.height === 'number';
  }

}
function rectsOverlap(
  a: Pick<InspectTextItem, 'x' | 'y' | 'width' | 'height'>,
  b: LinkRect
): boolean {
  return (
    a.x < b.x + b.width &&
    a.x + a.width > b.x &&
    a.y < b.y + b.height &&
    a.y + a.height > b.y
  );
}